/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as OceanSwimmingRouteImport } from './routes/ocean-swimming'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as KidsSwimmingRouteImport } from './routes/kids-swimming'
import { Route as FreedivingRouteImport } from './routes/freediving'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as AdultSwimmingRouteImport } from './routes/adult-swimming'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhilosophyTopicRouteImport } from './routes/philosophy.$topic'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const OceanSwimmingRoute = OceanSwimmingRouteImport.update({
  id: '/ocean-swimming',
  path: '/ocean-swimming',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsSwimmingRoute = KidsSwimmingRouteImport.update({
  id: '/kids-swimming',
  path: '/kids-swimming',
  getParentRoute: () => rootRouteImport,
} as any)
const FreedivingRoute = FreedivingRouteImport.update({
  id: '/freediving',
  path: '/freediving',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultSwimmingRoute = AdultSwimmingRouteImport.update({
  id: '/adult-swimming',
  path: '/adult-swimming',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyTopicRoute = PhilosophyTopicRouteImport.update({
  id: '/philosophy/$topic',
  path: '/philosophy/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adult-swimming': typeof AdultSwimmingRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/freediving': typeof FreedivingRoute
  '/kids-swimming': typeof KidsSwimmingRoute
  '/locations': typeof LocationsRoute
  '/ocean-swimming': typeof OceanSwimmingRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/philosophy/$topic': typeof PhilosophyTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adult-swimming': typeof AdultSwimmingRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/freediving': typeof FreedivingRoute
  '/kids-swimming': typeof KidsSwimmingRoute
  '/locations': typeof LocationsRoute
  '/ocean-swimming': typeof OceanSwimmingRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/philosophy/$topic': typeof PhilosophyTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adult-swimming': typeof AdultSwimmingRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/freediving': typeof FreedivingRoute
  '/kids-swimming': typeof KidsSwimmingRoute
  '/locations': typeof LocationsRoute
  '/ocean-swimming': typeof OceanSwimmingRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/philosophy/$topic': typeof PhilosophyTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adult-swimming'
    | '/coaches'
    | '/contact'
    | '/faq'
    | '/freediving'
    | '/kids-swimming'
    | '/locations'
    | '/ocean-swimming'
    | '/programs'
    | '/sitemap.xml'
    | '/philosophy/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adult-swimming'
    | '/coaches'
    | '/contact'
    | '/faq'
    | '/freediving'
    | '/kids-swimming'
    | '/locations'
    | '/ocean-swimming'
    | '/programs'
    | '/sitemap.xml'
    | '/philosophy/$topic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adult-swimming'
    | '/coaches'
    | '/contact'
    | '/faq'
    | '/freediving'
    | '/kids-swimming'
    | '/locations'
    | '/ocean-swimming'
    | '/programs'
    | '/sitemap.xml'
    | '/philosophy/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdultSwimmingRoute: typeof AdultSwimmingRoute
  CoachesRoute: typeof CoachesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FreedivingRoute: typeof FreedivingRoute
  KidsSwimmingRoute: typeof KidsSwimmingRoute
  LocationsRoute: typeof LocationsRoute
  OceanSwimmingRoute: typeof OceanSwimmingRoute
  ProgramsRoute: typeof ProgramsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PhilosophyTopicRoute: typeof PhilosophyTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocean-swimming': {
      id: '/ocean-swimming'
      path: '/ocean-swimming'
      fullPath: '/ocean-swimming'
      preLoaderRoute: typeof OceanSwimmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids-swimming': {
      id: '/kids-swimming'
      path: '/kids-swimming'
      fullPath: '/kids-swimming'
      preLoaderRoute: typeof KidsSwimmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freediving': {
      id: '/freediving'
      path: '/freediving'
      fullPath: '/freediving'
      preLoaderRoute: typeof FreedivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult-swimming': {
      id: '/adult-swimming'
      path: '/adult-swimming'
      fullPath: '/adult-swimming'
      preLoaderRoute: typeof AdultSwimmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy/$topic': {
      id: '/philosophy/$topic'
      path: '/philosophy/$topic'
      fullPath: '/philosophy/$topic'
      preLoaderRoute: typeof PhilosophyTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdultSwimmingRoute: AdultSwimmingRoute,
  CoachesRoute: CoachesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FreedivingRoute: FreedivingRoute,
  KidsSwimmingRoute: KidsSwimmingRoute,
  LocationsRoute: LocationsRoute,
  OceanSwimmingRoute: OceanSwimmingRoute,
  ProgramsRoute: ProgramsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PhilosophyTopicRoute: PhilosophyTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
